// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: orc_proxy.proto

#include "orc_proxy.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace orc_proxy {
namespace proto {
        template <typename>
PROTOBUF_CONSTEXPR Field::Field(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.value_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.kind_)*/ 0,
      /*decltype(_impl_.length_)*/ 0u,
    } {}
struct FieldDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FieldDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FieldDefaultTypeInternal() {}
  union {
    Field _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FieldDefaultTypeInternal _Field_default_instance_;
        template <typename>
PROTOBUF_CONSTEXPR Row::Row(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_.field_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
    } {}
struct RowDefaultTypeInternal {
  PROTOBUF_CONSTEXPR RowDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~RowDefaultTypeInternal() {}
  union {
    Row _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 RowDefaultTypeInternal _Row_default_instance_;
}  // namespace proto
}  // namespace orc_proxy
static ::_pb::Metadata file_level_metadata_orc_5fproxy_2eproto[2];
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_orc_5fproxy_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_orc_5fproxy_2eproto = nullptr;
const ::uint32_t TableStruct_orc_5fproxy_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::orc_proxy::proto::Field, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::orc_proxy::proto::Field, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::orc_proxy::proto::Field, _impl_.kind_),
    PROTOBUF_FIELD_OFFSET(::orc_proxy::proto::Field, _impl_.length_),
    PROTOBUF_FIELD_OFFSET(::orc_proxy::proto::Field, _impl_.value_),
    1,
    2,
    0,
    ~0u,  // no _has_bits_
    PROTOBUF_FIELD_OFFSET(::orc_proxy::proto::Row, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::orc_proxy::proto::Row, _impl_.field_),
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 11, -1, sizeof(::orc_proxy::proto::Field)},
        {14, -1, -1, sizeof(::orc_proxy::proto::Row)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::orc_proxy::proto::_Field_default_instance_._instance,
    &::orc_proxy::proto::_Row_default_instance_._instance,
};
const char descriptor_table_protodef_orc_5fproxy_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\017orc_proxy.proto\022\017orc_proxy.proto\"\274\002\n\005F"
    "ield\022)\n\004kind\030\001 \001(\0162\033.orc_proxy.proto.Fie"
    "ld.Kind\022\016\n\006length\030\002 \001(\r\022\r\n\005value\030\003 \001(\014\"\350"
    "\001\n\004Kind\022\013\n\007BOOLEAN\020\000\022\010\n\004BYTE\020\001\022\t\n\005SHORT\020"
    "\002\022\007\n\003INT\020\003\022\010\n\004LONG\020\004\022\t\n\005FLOAT\020\005\022\n\n\006DOUBL"
    "E\020\006\022\n\n\006STRING\020\007\022\n\n\006BINARY\020\010\022\r\n\tTIMESTAMP"
    "\020\t\022\010\n\004LIST\020\n\022\007\n\003MAP\020\013\022\n\n\006STRUCT\020\014\022\t\n\005UNI"
    "ON\020\r\022\013\n\007DECIMAL\020\016\022\010\n\004DATE\020\017\022\013\n\007VARCHAR\020\020"
    "\022\010\n\004CHAR\020\021\022\025\n\021TIMESTAMP_INSTANT\020\022\",\n\003Row"
    "\022%\n\005field\030\001 \003(\0132\026.orc_proxy.proto.FieldB"
    "\002Z\000"
};
static ::absl::once_flag descriptor_table_orc_5fproxy_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_orc_5fproxy_2eproto = {
    false,
    false,
    403,
    descriptor_table_protodef_orc_5fproxy_2eproto,
    "orc_proxy.proto",
    &descriptor_table_orc_5fproxy_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_orc_5fproxy_2eproto::offsets,
    file_level_metadata_orc_5fproxy_2eproto,
    file_level_enum_descriptors_orc_5fproxy_2eproto,
    file_level_service_descriptors_orc_5fproxy_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_orc_5fproxy_2eproto_getter() {
  return &descriptor_table_orc_5fproxy_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_orc_5fproxy_2eproto(&descriptor_table_orc_5fproxy_2eproto);
namespace orc_proxy {
namespace proto {
const ::google::protobuf::EnumDescriptor* Field_Kind_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_orc_5fproxy_2eproto);
  return file_level_enum_descriptors_orc_5fproxy_2eproto[0];
}
bool Field_Kind_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
    case 8:
    case 9:
    case 10:
    case 11:
    case 12:
    case 13:
    case 14:
    case 15:
    case 16:
    case 17:
    case 18:
      return true;
    default:
      return false;
  }
}
#if (__cplusplus < 201703) && \
  (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))

constexpr Field_Kind Field::BOOLEAN;
constexpr Field_Kind Field::BYTE;
constexpr Field_Kind Field::SHORT;
constexpr Field_Kind Field::INT;
constexpr Field_Kind Field::LONG;
constexpr Field_Kind Field::FLOAT;
constexpr Field_Kind Field::DOUBLE;
constexpr Field_Kind Field::STRING;
constexpr Field_Kind Field::BINARY;
constexpr Field_Kind Field::TIMESTAMP;
constexpr Field_Kind Field::LIST;
constexpr Field_Kind Field::MAP;
constexpr Field_Kind Field::STRUCT;
constexpr Field_Kind Field::UNION;
constexpr Field_Kind Field::DECIMAL;
constexpr Field_Kind Field::DATE;
constexpr Field_Kind Field::VARCHAR;
constexpr Field_Kind Field::CHAR;
constexpr Field_Kind Field::TIMESTAMP_INSTANT;
constexpr Field_Kind Field::Kind_MIN;
constexpr Field_Kind Field::Kind_MAX;
constexpr int Field::Kind_ARRAYSIZE;

#endif  // (__cplusplus < 201703) &&
        // (!defined(_MSC_VER) || (_MSC_VER >= 1900 && _MSC_VER < 1912))
// ===================================================================

class Field::_Internal {
 public:
  using HasBits = decltype(std::declval<Field>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(Field, _impl_._has_bits_);
  static void set_has_kind(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_length(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_value(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

Field::Field(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:orc_proxy.proto.Field)
}
Field::Field(const Field& from) : ::google::protobuf::Message() {
  Field* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.value_){},
      decltype(_impl_.kind_){},
      decltype(_impl_.length_){},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.value_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.value_.Set(from._internal_value(), _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.kind_, &from._impl_.kind_,
    static_cast<::size_t>(reinterpret_cast<char*>(&_impl_.length_) -
    reinterpret_cast<char*>(&_impl_.kind_)) + sizeof(_impl_.length_));

  // @@protoc_insertion_point(copy_constructor:orc_proxy.proto.Field)
}
inline void Field::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.value_){},
      decltype(_impl_.kind_){0},
      decltype(_impl_.length_){0u},
  };
  _impl_.value_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.value_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
Field::~Field() {
  // @@protoc_insertion_point(destructor:orc_proxy.proto.Field)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Field::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.value_.Destroy();
}
void Field::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Field::Clear() {
// @@protoc_insertion_point(message_clear_start:orc_proxy.proto.Field)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    _impl_.value_.ClearNonDefaultToEmpty();
  }
  if (cached_has_bits & 0x00000006u) {
    ::memset(&_impl_.kind_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.length_) -
        reinterpret_cast<char*>(&_impl_.kind_)) + sizeof(_impl_.length_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Field::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> Field::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Field, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Field_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional .orc_proxy.proto.Field.Kind kind = 1;
    {::_pbi::TcParser::FastEr0S1,
     {8, 1, 18, PROTOBUF_FIELD_OFFSET(Field, _impl_.kind_)}},
    // optional uint32 length = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Field, _impl_.length_), 2>(),
     {16, 2, 0, PROTOBUF_FIELD_OFFSET(Field, _impl_.length_)}},
    // optional bytes value = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 0, 0, PROTOBUF_FIELD_OFFSET(Field, _impl_.value_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .orc_proxy.proto.Field.Kind kind = 1;
    {PROTOBUF_FIELD_OFFSET(Field, _impl_.kind_), _Internal::kHasBitsOffset + 1, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional uint32 length = 2;
    {PROTOBUF_FIELD_OFFSET(Field, _impl_.length_), _Internal::kHasBitsOffset + 2, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional bytes value = 3;
    {PROTOBUF_FIELD_OFFSET(Field, _impl_.value_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
  }}, {{
    {0, 19},
  }}, {{
  }},
};

::uint8_t* Field::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:orc_proxy.proto.Field)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  // optional .orc_proxy.proto.Field.Kind kind = 1;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this->_internal_kind(), target);
  }

  // optional uint32 length = 2;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_length(), target);
  }

  // optional bytes value = 3;
  if (cached_has_bits & 0x00000001u) {
    const std::string& _s = this->_internal_value();
    target = stream->WriteBytesMaybeAliased(3, _s, target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:orc_proxy.proto.Field)
  return target;
}

::size_t Field::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:orc_proxy.proto.Field)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    // optional bytes value = 3;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this->_internal_value());
    }

    // optional .orc_proxy.proto.Field.Kind kind = 1;
    if (cached_has_bits & 0x00000002u) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this->_internal_kind());
    }

    // optional uint32 length = 2;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this->_internal_length());
    }

  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Field::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    Field::MergeImpl
};
const ::google::protobuf::Message::ClassData*Field::GetClassData() const { return &_class_data_; }


void Field::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Field*>(&to_msg);
  auto& from = static_cast<const Field&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:orc_proxy.proto.Field)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      _this->_internal_set_value(from._internal_value());
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.kind_ = from._impl_.kind_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.length_ = from._impl_.length_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Field::CopyFrom(const Field& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:orc_proxy.proto.Field)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Field::IsInitialized() const {
  return true;
}

void Field::InternalSwap(Field* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.value_, lhs_arena,
                                       &other->_impl_.value_, rhs_arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Field, _impl_.length_)
      + sizeof(Field::_impl_.length_)
      - PROTOBUF_FIELD_OFFSET(Field, _impl_.kind_)>(
          reinterpret_cast<char*>(&_impl_.kind_),
          reinterpret_cast<char*>(&other->_impl_.kind_));
}

::google::protobuf::Metadata Field::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_orc_5fproxy_2eproto_getter, &descriptor_table_orc_5fproxy_2eproto_once,
      file_level_metadata_orc_5fproxy_2eproto[0]);
}
// ===================================================================

class Row::_Internal {
 public:
};

Row::Row(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:orc_proxy.proto.Row)
}
Row::Row(const Row& from) : ::google::protobuf::Message() {
  Row* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.field_){from._impl_.field_},
      /*decltype(_impl_._cached_size_)*/ {},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:orc_proxy.proto.Row)
}
inline void Row::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_.field_){arena},
      /*decltype(_impl_._cached_size_)*/ {},
  };
}
Row::~Row() {
  // @@protoc_insertion_point(destructor:orc_proxy.proto.Row)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Row::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.field_.~RepeatedPtrField();
}
void Row::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void Row::Clear() {
// @@protoc_insertion_point(message_clear_start:orc_proxy.proto.Row)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_field()->Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* Row::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> Row::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_Row_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    // repeated .orc_proxy.proto.Field field = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Row, _impl_.field_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .orc_proxy.proto.Field field = 1;
    {PROTOBUF_FIELD_OFFSET(Row, _impl_.field_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::orc_proxy::proto::Field>()},
  }}, {{
  }},
};

::uint8_t* Row::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:orc_proxy.proto.Row)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .orc_proxy.proto.Field field = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_field_size()); i < n; i++) {
    const auto& repfield = this->_internal_field().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:orc_proxy.proto.Row)
  return target;
}

::size_t Row::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:orc_proxy.proto.Row)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .orc_proxy.proto.Field field = 1;
  total_size += 1UL * this->_internal_field_size();
  for (const auto& msg : this->_internal_field()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData Row::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    Row::MergeImpl
};
const ::google::protobuf::Message::ClassData*Row::GetClassData() const { return &_class_data_; }


void Row::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<Row*>(&to_msg);
  auto& from = static_cast<const Row&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:orc_proxy.proto.Row)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_field()->MergeFrom(from._internal_field());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Row::CopyFrom(const Row& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:orc_proxy.proto.Row)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Row::IsInitialized() const {
  return true;
}

void Row::InternalSwap(Row* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.field_.InternalSwap(&other->_impl_.field_);
}

::google::protobuf::Metadata Row::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_orc_5fproxy_2eproto_getter, &descriptor_table_orc_5fproxy_2eproto_once,
      file_level_metadata_orc_5fproxy_2eproto[1]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace proto
}  // namespace orc_proxy
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
