// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.20.1
// source: orc_wrap.proto

package orc_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type_Kind int32

const (
	Type_BOOLEAN           Type_Kind = 0
	Type_BYTE              Type_Kind = 1
	Type_SHORT             Type_Kind = 2
	Type_INT               Type_Kind = 3
	Type_LONG              Type_Kind = 4
	Type_FLOAT             Type_Kind = 5
	Type_DOUBLE            Type_Kind = 6
	Type_STRING            Type_Kind = 7
	Type_BINARY            Type_Kind = 8
	Type_TIMESTAMP         Type_Kind = 9
	Type_LIST              Type_Kind = 10
	Type_MAP               Type_Kind = 11
	Type_STRUCT            Type_Kind = 12
	Type_UNION             Type_Kind = 13
	Type_DECIMAL           Type_Kind = 14
	Type_DATE              Type_Kind = 15
	Type_VARCHAR           Type_Kind = 16
	Type_CHAR              Type_Kind = 17
	Type_TIMESTAMP_INSTANT Type_Kind = 18
)

// Enum value maps for Type_Kind.
var (
	Type_Kind_name = map[int32]string{
		0:  "BOOLEAN",
		1:  "BYTE",
		2:  "SHORT",
		3:  "INT",
		4:  "LONG",
		5:  "FLOAT",
		6:  "DOUBLE",
		7:  "STRING",
		8:  "BINARY",
		9:  "TIMESTAMP",
		10: "LIST",
		11: "MAP",
		12: "STRUCT",
		13: "UNION",
		14: "DECIMAL",
		15: "DATE",
		16: "VARCHAR",
		17: "CHAR",
		18: "TIMESTAMP_INSTANT",
	}
	Type_Kind_value = map[string]int32{
		"BOOLEAN":           0,
		"BYTE":              1,
		"SHORT":             2,
		"INT":               3,
		"LONG":              4,
		"FLOAT":             5,
		"DOUBLE":            6,
		"STRING":            7,
		"BINARY":            8,
		"TIMESTAMP":         9,
		"LIST":              10,
		"MAP":               11,
		"STRUCT":            12,
		"UNION":             13,
		"DECIMAL":           14,
		"DATE":              15,
		"VARCHAR":           16,
		"CHAR":              17,
		"TIMESTAMP_INSTANT": 18,
	}
)

func (x Type_Kind) Enum() *Type_Kind {
	p := new(Type_Kind)
	*p = x
	return p
}

func (x Type_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_orc_wrap_proto_enumTypes[0].Descriptor()
}

func (Type_Kind) Type() protoreflect.EnumType {
	return &file_orc_wrap_proto_enumTypes[0]
}

func (x Type_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type_Kind.Descriptor instead.
func (Type_Kind) EnumDescriptor() ([]byte, []int) {
	return file_orc_wrap_proto_rawDescGZIP(), []int{0, 0}
}

type Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind          *Type_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=orc_proto.Type_Kind,oneof" json:"kind,omitempty"`
	Subtypes      []uint32   `protobuf:"varint,2,rep,packed,name=subtypes,proto3" json:"subtypes,omitempty"`
	FieldNames    []string   `protobuf:"bytes,3,rep,name=fieldNames,proto3" json:"fieldNames,omitempty"`
	MaximumLength *uint32    `protobuf:"varint,4,opt,name=maximumLength,proto3,oneof" json:"maximumLength,omitempty"`
	Precision     *uint32    `protobuf:"varint,5,opt,name=precision,proto3,oneof" json:"precision,omitempty"`
	Scale         *uint32    `protobuf:"varint,6,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
}

func (x *Type) Reset() {
	*x = Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_wrap_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Type) ProtoMessage() {}

func (x *Type) ProtoReflect() protoreflect.Message {
	mi := &file_orc_wrap_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Type.ProtoReflect.Descriptor instead.
func (*Type) Descriptor() ([]byte, []int) {
	return file_orc_wrap_proto_rawDescGZIP(), []int{0}
}

func (x *Type) GetKind() Type_Kind {
	if x != nil && x.Kind != nil {
		return *x.Kind
	}
	return Type_BOOLEAN
}

func (x *Type) GetSubtypes() []uint32 {
	if x != nil {
		return x.Subtypes
	}
	return nil
}

func (x *Type) GetFieldNames() []string {
	if x != nil {
		return x.FieldNames
	}
	return nil
}

func (x *Type) GetMaximumLength() uint32 {
	if x != nil && x.MaximumLength != nil {
		return *x.MaximumLength
	}
	return 0
}

func (x *Type) GetPrecision() uint32 {
	if x != nil && x.Precision != nil {
		return *x.Precision
	}
	return 0
}

func (x *Type) GetScale() uint32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

// Field represents a field in a row;
type Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// kind specifies the type of field;
	Type   *Type   `protobuf:"bytes,1,opt,name=type,proto3,oneof" json:"type,omitempty"`
	I      *int64  `protobuf:"varint,2,opt,name=i,proto3,oneof" json:"i,omitempty"`
	Value  []byte  `protobuf:"bytes,4,opt,name=value,proto3,oneof" json:"value,omitempty"`
	Length *uint32 `protobuf:"varint,3,opt,name=length,proto3,oneof" json:"length,omitempty"`
}

func (x *Field) Reset() {
	*x = Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_wrap_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Field) ProtoMessage() {}

func (x *Field) ProtoReflect() protoreflect.Message {
	mi := &file_orc_wrap_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Field.ProtoReflect.Descriptor instead.
func (*Field) Descriptor() ([]byte, []int) {
	return file_orc_wrap_proto_rawDescGZIP(), []int{1}
}

func (x *Field) GetType() *Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *Field) GetI() int64 {
	if x != nil && x.I != nil {
		return *x.I
	}
	return 0
}

func (x *Field) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Field) GetLength() uint32 {
	if x != nil && x.Length != nil {
		return *x.Length
	}
	return 0
}

type Row struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Field []*Field `protobuf:"bytes,1,rep,name=field,proto3" json:"field,omitempty"`
}

func (x *Row) Reset() {
	*x = Row{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orc_wrap_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_orc_wrap_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_orc_wrap_proto_rawDescGZIP(), []int{2}
}

func (x *Row) GetField() []*Field {
	if x != nil {
		return x.Field
	}
	return nil
}

var File_orc_wrap_proto protoreflect.FileDescriptor

var file_orc_wrap_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6f, 0x72, 0x63, 0x5f, 0x77, 0x72, 0x61, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x09, 0x6f, 0x72, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xfc, 0x03, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x2d, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6f, 0x72, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64,
	0x88, 0x01, 0x01, 0x12, 0x1e, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0d, 0x42, 0x02, 0x10, 0x01, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65,
	0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61,
	0x6d, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x0d, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x4c, 0x65,
	0x6e, 0x67, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x01, 0x52, 0x0d, 0x6d, 0x61,
	0x78, 0x69, 0x6d, 0x75, 0x6d, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x88, 0x01, 0x01, 0x12, 0x21,
	0x0a, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0d, 0x48, 0x02, 0x52, 0x09, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d,
	0x48, 0x03, 0x52, 0x05, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x88, 0x01, 0x01, 0x22, 0xe8, 0x01, 0x0a,
	0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x4f, 0x4f, 0x4c, 0x45, 0x41, 0x4e,
	0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x59, 0x54, 0x45, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x53, 0x48, 0x4f, 0x52, 0x54, 0x10, 0x02, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e, 0x54, 0x10, 0x03,
	0x12, 0x08, 0x0a, 0x04, 0x4c, 0x4f, 0x4e, 0x47, 0x10, 0x04, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c,
	0x4f, 0x41, 0x54, 0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10,
	0x06, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x07, 0x12, 0x0a, 0x0a,
	0x06, 0x42, 0x49, 0x4e, 0x41, 0x52, 0x59, 0x10, 0x08, 0x12, 0x0d, 0x0a, 0x09, 0x54, 0x49, 0x4d,
	0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x10, 0x09, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x49, 0x53, 0x54,
	0x10, 0x0a, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x41, 0x50, 0x10, 0x0b, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x54, 0x52, 0x55, 0x43, 0x54, 0x10, 0x0c, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x49, 0x4f, 0x4e,
	0x10, 0x0d, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x45, 0x43, 0x49, 0x4d, 0x41, 0x4c, 0x10, 0x0e, 0x12,
	0x08, 0x0a, 0x04, 0x44, 0x41, 0x54, 0x45, 0x10, 0x0f, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x41, 0x52,
	0x43, 0x48, 0x41, 0x52, 0x10, 0x10, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x48, 0x41, 0x52, 0x10, 0x11,
	0x12, 0x15, 0x0a, 0x11, 0x54, 0x49, 0x4d, 0x45, 0x53, 0x54, 0x41, 0x4d, 0x50, 0x5f, 0x49, 0x4e,
	0x53, 0x54, 0x41, 0x4e, 0x54, 0x10, 0x12, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6b, 0x69, 0x6e, 0x64,
	0x42, 0x10, 0x0a, 0x0e, 0x5f, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x4c, 0x65, 0x6e, 0x67,
	0x74, 0x68, 0x42, 0x0c, 0x0a, 0x0a, 0x5f, 0x70, 0x72, 0x65, 0x63, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x42, 0x08, 0x0a, 0x06, 0x5f, 0x73, 0x63, 0x61, 0x6c, 0x65, 0x22, 0xa0, 0x01, 0x0a, 0x05, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x72, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x54,
	0x79, 0x70, 0x65, 0x48, 0x00, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x88, 0x01, 0x01, 0x12, 0x11,
	0x0a, 0x01, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x48, 0x01, 0x52, 0x01, 0x69, 0x88, 0x01,
	0x01, 0x12, 0x19, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c,
	0x48, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x48, 0x03, 0x52, 0x06,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x42, 0x04, 0x0a, 0x02, 0x5f, 0x69, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x42, 0x09, 0x0a, 0x07, 0x5f, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x2d, 0x0a,
	0x03, 0x52, 0x6f, 0x77, 0x12, 0x26, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x72, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x0d, 0x5a, 0x0b,
	0x2e, 0x2f, 0x6f, 0x72, 0x63, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_orc_wrap_proto_rawDescOnce sync.Once
	file_orc_wrap_proto_rawDescData = file_orc_wrap_proto_rawDesc
)

func file_orc_wrap_proto_rawDescGZIP() []byte {
	file_orc_wrap_proto_rawDescOnce.Do(func() {
		file_orc_wrap_proto_rawDescData = protoimpl.X.CompressGZIP(file_orc_wrap_proto_rawDescData)
	})
	return file_orc_wrap_proto_rawDescData
}

var file_orc_wrap_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orc_wrap_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_orc_wrap_proto_goTypes = []interface{}{
	(Type_Kind)(0), // 0: orc_proto.Type.Kind
	(*Type)(nil),   // 1: orc_proto.Type
	(*Field)(nil),  // 2: orc_proto.Field
	(*Row)(nil),    // 3: orc_proto.Row
}
var file_orc_wrap_proto_depIdxs = []int32{
	0, // 0: orc_proto.Type.kind:type_name -> orc_proto.Type.Kind
	1, // 1: orc_proto.Field.type:type_name -> orc_proto.Type
	2, // 2: orc_proto.Row.field:type_name -> orc_proto.Field
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_orc_wrap_proto_init() }
func file_orc_wrap_proto_init() {
	if File_orc_wrap_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orc_wrap_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_wrap_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orc_wrap_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Row); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_orc_wrap_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_orc_wrap_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orc_wrap_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orc_wrap_proto_goTypes,
		DependencyIndexes: file_orc_wrap_proto_depIdxs,
		EnumInfos:         file_orc_wrap_proto_enumTypes,
		MessageInfos:      file_orc_wrap_proto_msgTypes,
	}.Build()
	File_orc_wrap_proto = out.File
	file_orc_wrap_proto_rawDesc = nil
	file_orc_wrap_proto_goTypes = nil
	file_orc_wrap_proto_depIdxs = nil
}
